name: E2E_and_Deploy

on:
  push:
    branches: 'main'

jobs:
  eslint_and_build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Run Eslint
        run: npm run eslint
      - name: Create React Build
        run: npm run build --if-present

#      - name: Upload React Build Artifact
#        uses: actions/upload-artifact@v3
#        with:
#         name: react_build
#         path: ${{ github.workspace }}/build

  cypress_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 19.x ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v3
        with:
          project: .
          browser: chrome
          start: npm start
          wait-on: "http://localhost:3000"
          command: npm run cypress:run

  deploy:
    needs: [eslint_and_build, cypress_tests]

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to production - render.com
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
